# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-06-12.
# BFM-2017 loader (Python proof-of-concept). Mirrors the future C++ BFMLoader.
#
# The BFM is a GENERATOR: shape(alpha) -> 3D mesh. It does NOT analyse images.
# =============================================================================
import h5py
import numpy as np


class BFM:
    def __init__(self, path):
        with h5py.File(path, "r") as f:
            # shape: identity model
            self.shape_mean = f["shape/model/mean"][:].astype(np.float64)        # (3N,)
            self.shape_basis = f["shape/model/pcaBasis"][:].astype(np.float64)   # (3N, 199)
            self.shape_std = np.sqrt(f["shape/model/pcaVariance"][:].astype(np.float64))
            # colour / albedo model (per-vertex RGB)
            self.color_mean = f["color/model/mean"][:].astype(np.float64)        # (3N,)
            # topology
            self.triangles = f["shape/representer/cells"][:].astype(np.int64).T  # (M, 3)

        self.n_vertices = self.shape_mean.size // 3
        print(f"[BFM] {self.n_vertices} vertices, "
              f"{self.shape_basis.shape[1]} shape components, "
              f"{self.triangles.shape[0]} triangles")

    def shape(self, alpha):
        """Generate a face geometry from identity coefficients alpha (in mm).

        vertices = mean + basis * (alpha .* sigma)    (paper Sec. 1)
        alpha is standard-normal-scaled; we multiply by sigma = sqrt(variance).
        Returns (N, 3) in millimetres.
        """
        k = len(alpha)
        v = self.shape_mean + self.shape_basis[:, :k] @ (alpha * self.shape_std[:k])
        return v.reshape(-1, 3)

    def mean_shape(self):
        """The average face (alpha = 0), (N, 3) in millimetres."""
        return self.shape_mean.reshape(-1, 3)

    def albedo(self):
        """Per-vertex RGB colour in [0, 1], (N, 3)."""
        c = self.color_mean.reshape(-1, 3)
        if c.max() > 1.5:        # stored as 0..255 in some models
            c = c / 255.0
        return np.clip(c, 0.0, 1.0)
