# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-06-12.
# BFM-2017 loader (Python proof-of-concept). Mirrors the future C++ BFMLoader.
#
# The BFM is a GENERATOR: shape(alpha) -> 3D mesh. It does NOT analyse images.
# =============================================================================
from unicodedata import name

import h5py
import numpy as np
import json

class BFM:
    def __init__(self, path):
        with h5py.File(path, "r") as f:
            # shape: identity model
            self.shape_mean = f["shape/model/mean"][:].astype(np.float64)        # (3N,)
            self.shape_basis = f["shape/model/pcaBasis"][:].astype(np.float64)   # (3N, 199)
            self.shape_std = np.sqrt(f["shape/model/pcaVariance"][:].astype(np.float64))
            # colour / albedo model (per-vertex RGB)
            self.color_mean = f["color/model/mean"][:].astype(np.float64)        # (3N,)
            # topology
            self.triangles = f["shape/representer/cells"][:].astype(np.int64).T  # (M, 3)
            # named landmarks from the BFM metadata
            self.bfm_landmarks = self._load_landmarks(f)
            if not self.bfm_landmarks:
                print("[BFM] WARNING: no BFM landmarks were loaded")
            else:
                for name, vertex_idx in list(self.bfm_landmarks.items())[:10]:
                    print(f"[BFM] landmark {name} -> vertex {vertex_idx}")

        self.n_vertices = self.shape_mean.size // 3
        print(f"[BFM] {self.n_vertices} vertices, "
              f"{self.shape_basis.shape[1]} shape components, "
              f"{self.triangles.shape[0]} triangles")
        print(f"[BFM] {len(self.bfm_landmarks)} named landmark mappings")

    def shape(self, alpha):
        """Generate a face geometry from identity coefficients alpha (in mm).

        vertices = mean + basis * (alpha .* sigma)    (paper Sec. 1)
        alpha is standard-normal-scaled; we multiply by sigma = sqrt(variance).
        Returns (N, 3) in millimetres.
        """
        k = len(alpha)
        v = self.shape_mean + self.shape_basis[:, :k] @ (alpha * self.shape_std[:k])
        return v.reshape(-1, 3)

    def mean_shape(self):
        """The average face (alpha = 0), (N, 3) in millimetres."""
        return self.shape_mean.reshape(-1, 3)

    def landmark_index(self, name):
        """Return the BFM vertex index for a named landmark, or -1 if missing."""
        return self.bfm_landmarks.get(name, -1)

    def landmarks(self):
        """Return the BFM landmark name -> vertex index map."""
        return dict(self.bfm_landmarks)

    def albedo(self):
        """Per-vertex RGB colour in [0, 1], (N, 3)."""
        c = self.color_mean.reshape(-1, 3)
        if c.max() > 1.5:        # stored as 0..255 in some models
            c = c / 255.0
        return np.clip(c, 0.0, 1.0)

    def _load_landmarks(self, f):
        mean_shape = self.mean_shape()

        coordinates = {}

        if "metadata/landmarks/json" in f:
            raw = f["metadata/landmarks/json"][()]

            if isinstance(raw, bytes):
                text = raw.decode("utf-8", errors="ignore")
            else:
                text = raw.tobytes().decode("utf-8", errors="ignore")

            parsed = json.loads(text)

            for name, xyz in parsed.items():
                coordinates[name] = np.asarray(xyz, dtype=np.float64)

        elif "metadata/landmarks/text" in f:
            raw = f["metadata/landmarks/text"][()]

            if isinstance(raw, bytes):
                text = raw.decode("utf-8", errors="ignore")
            else:
                text = raw.tobytes().decode("utf-8", errors="ignore")

            for line in text.splitlines():
                line = line.strip()

                if not line:
                    continue

                parts = line.split()

                if len(parts) < 4:
                    continue

                name = parts[0]

                try:
                    coordinates[name] = np.array(
                        [
                            float(parts[-3]),
                            float(parts[-2]),
                            float(parts[-1]),
                        ],
                        dtype=np.float64,
                    )
                except ValueError:
                    continue

        else:
            print("[BFM] WARNING: no landmark metadata found")
            return {}

        names = {}

        for name, xyz in coordinates.items():
            dists = np.linalg.norm(mean_shape - xyz.reshape(1, 3), axis=1)
            names[name] = int(np.argmin(dists))

        return names