# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-07-02.
# Standalone sanity check for a downloaded Biwi sequence: decodes the depth
# RLE, parses the calibration, and verifies the RGB<->depth registration by
# splatting the head point cloud onto the RGB image. Run this FIRST after
# python/get_biwi.py, before wiring anything into the pipeline.
#
#   python3 python/check_biwi.py [seq] [frame]     # defaults: 01, first frame
#
# Output: data/out/biwi_check_<seq>.png — the head cloud (green) must sit ON
# the person's head, the pose head-centre (red circle) on the face.
# =============================================================================
import os
import sys

import cv2
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import biwi  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "data", "biwi")


def main():
    seq = sys.argv[1] if len(sys.argv) > 1 else "01"
    frames = biwi.list_frames(os.path.join(ROOT, seq))
    if not frames:
        raise SystemExit(f"no frames in {ROOT}/{seq} — run python/get_biwi.py {seq}")
    frame_no = int(sys.argv[2]) if len(sys.argv) > 2 else frames[0]

    f = biwi.BiwiFrame(ROOT, seq, frame_no)
    nonzero = f.depth_mm[f.depth_mm > 0]
    print(f"sequence {seq}, frame {frame_no}  ({len(frames)} frames total)")
    print(f"  rgb   : {f.rgb.shape}")
    print(f"  depth : {f.depth_mm.shape}, {100 * nonzero.size / f.depth_mm.size:.1f}% "
          f"non-zero, median {np.median(nonzero):.0f} mm")
    print(f"  K_depth fx={f.K_depth[0, 0]:.1f}  K_rgb fx={f.K_rgb[0, 0]:.1f}  "
          f"baseline |t|={np.linalg.norm(f.t_rgb_mm):.1f} mm")
    print(f"  head centre (depth cam, mm): {np.round(f.head_center_mm, 1)}")

    cloud = biwi.backproject_mm(f.depth_mm, f.K_depth)
    head = biwi.crop_head_mm(cloud, f.head_center_mm, radius=250.0, front_slab=500.0)
    in_rgb = biwi.depth_to_rgb_cam(head, f.R_rgb, f.t_rgb_mm)
    uv = biwi.project(in_rgb, f.K_rgb).round().astype(int)

    h, w = f.rgb.shape[:2]
    inside = (uv[:, 0] >= 0) & (uv[:, 0] < w) & (uv[:, 1] >= 0) & (uv[:, 1] < h)
    print(f"  head cloud: {len(head)} pts, {100 * inside.mean():.1f}% project "
          f"into the RGB frame")

    overlay = cv2.cvtColor(f.rgb, cv2.COLOR_RGB2BGR)
    overlay[uv[inside, 1], uv[inside, 0]] = (0, 255, 0)
    centre = biwi.project(biwi.depth_to_rgb_cam(
        f.head_center_mm.reshape(1, 3), f.R_rgb, f.t_rgb_mm), f.K_rgb)[0]
    cv2.circle(overlay, (int(centre[0]), int(centre[1])), 8, (0, 0, 255), 2)

    out_dir = os.path.join(os.path.dirname(ROOT), "out")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"biwi_check_{seq}.png")
    cv2.imwrite(out_path, overlay)
    print(f"  wrote {out_path} — green cloud must sit on the head")


if __name__ == "__main__":
    main()
