# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-06-12.
# Standalone sanity check for the BFM .h5: prints the HDF5 layout and the few
# shapes the pipeline depends on. Run this FIRST if anything looks off.
#
#   python3 python/check_bfm.py
# =============================================================================
import sys

import h5py
import numpy as np

DEFAULT = "data/bfm/model2017-1_bfm_nomouth.h5"


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    print(f"Opening: {path}\n")
    with h5py.File(path, "r") as f:
        print("=== structure ===")
        f.visititems(lambda n, o: print(f"  {n:42s} {getattr(o, 'shape', '')}")
                     if isinstance(o, h5py.Dataset) else None)

        print("\n=== key datasets ===")
        for key in ["shape/model/mean", "shape/model/pcaBasis", "shape/model/pcaVariance",
                    "expression/model/pcaBasis", "color/model/mean",
                    "shape/representer/cells"]:
            print(f"  {key:32s} {'OK ' + str(f[key].shape) if key in f else 'MISSING'}")

        mean = f["shape/model/mean"][:]
        var = f["shape/model/pcaVariance"][:]
        print(f"\n  vertices              = {mean.shape[0] // 3}")
        print(f"  shape components      = {var.shape[0]}")
        print(f"  sigma = sqrt(var)[:5] = {np.round(np.sqrt(var[:5]), 2)}")
        print("  (sigma is the std-dev you divide by in the regulariser E_reg)")


if __name__ == "__main__":
    main()
