# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-06-12.
# Analysis-by-synthesis fit (Python proof-of-concept). Mirrors C++ Optimizer.
#
# PROOF OF CONCEPT, not the final method. It fits the BFM to the DEPTH point
# cloud (the RGB-D modality) with iterative-closest-point + Levenberg-Marquardt:
#
#   parameters p = [ rotation(3, axis-angle), translation(3),
#                    log-scale(1), shape coeffs alpha(K) ]
#
# Each outer iteration:
#   1. transform the model with the current p
#   2. find, for every target point, the nearest model vertex   (ICP correspondences)
#   3. run Levenberg-Marquardt to reduce  ||model - target||^2 + reg*||alpha||^2
#
# The dense PHOTOMETRIC term, the SPARSE landmark term and EXPRESSION are left
# out on purpose -- those are the later milestones. This already demonstrates the
# loop: "predict the face parameters in N iterations".
# =============================================================================
import numpy as np
from scipy.optimize import least_squares
from scipy.spatial import cKDTree


def axis_angle_to_R(r):
    """Rodrigues' formula: axis-angle vector (3,) -> rotation matrix (3, 3)."""
    theta = np.linalg.norm(r)
    if theta < 1e-12:
        return np.eye(3)
    k = r / theta
    K = np.array([[0, -k[2], k[1]],
                  [k[2], 0, -k[0]],
                  [-k[1], k[0], 0]])
    return np.eye(3) + np.sin(theta) * K + (1 - np.cos(theta)) * (K @ K)


class Fitter:
    def __init__(self, bfm, n_shape=30, reg=2.0, n_model_pts=6000):
        self.n_shape = n_shape
        self.reg = reg

        # Subsample the model vertices for speed (full mesh = 53k vertices).
        stride = max(1, bfm.n_vertices // n_model_pts)
        sub = np.arange(0, bfm.n_vertices, stride)
        rows = (3 * sub[:, None] + np.array([0, 1, 2])).reshape(-1)  # (3S,)

        # Everything in MILLIMETRES (the BFM's native unit), centred on the
        # mean-face centroid. Working in mm keeps the regulariser physically
        # meaningful: reg ~ (depth noise in mm)^2.
        self.mean_sub = bfm.shape_mean[rows].reshape(-1, 3)                 # (S, 3) mm
        self.basis_sub = bfm.shape_basis[rows][:, :n_shape].reshape(-1, 3, n_shape)  # mm
        self.std = bfm.shape_std[:n_shape]
        self.c0 = self.mean_sub.mean(axis=0)

        # 180 deg about Y: BFM looks +z, we want the face looking at the camera (-z).
        self.R_init = np.diag([-1.0, 1.0, -1.0])

    # ---- the parametric model: p -> world-space vertices ---------------------
    def model_points(self, p):
        alpha = p[7:]
        V = self.mean_sub + (self.basis_sub * (alpha * self.std)).sum(axis=2)  # (S, 3)
        V = V - self.c0
        R = axis_angle_to_R(p[:3])
        s = np.exp(p[6])
        return (s * (R @ (self.R_init @ V.T))).T + p[3:6]

    # ---- run the fit ---------------------------------------------------------
    def fit(self, target, n_iters=12, trim_percentile=80):
        target = np.asarray(target)
        K = self.n_shape

        # Initialise: translation = target centroid, scale = 1, no rotation, mean shape.
        p = np.r_[0.0, 0.0, 0.0, target.mean(axis=0), 0.0, np.zeros(K)]

        # Plausible bounds keep the problem well-posed (this is what stops the
        # model from ballooning or alpha from overfitting):
        #   scale in [0.8, 1.3],  each alpha in [-3 sigma, +3 sigma].
        lo = np.r_[[-np.pi] * 3, [-np.inf] * 3, np.log(0.8), [-3.0] * K]
        hi = np.r_[[np.pi] * 3, [np.inf] * 3, np.log(1.3), [3.0] * K]

        print(f"[fit] target points: {len(target)},  params: {len(p)}")
        for it in range(n_iters):
            # 1+2. correspondences: nearest model vertex per target point
            dist, idx = cKDTree(self.model_points(p)).query(target)

            # robust ICP: drop the worst correspondences (neck / outliers)
            thresh = np.percentile(dist, trim_percentile)
            keep = dist <= thresh
            tgt, idx_k = target[keep], idx[keep]

            # 3. Levenberg-Marquardt step with these fixed correspondences
            def residual(p_):
                mp = self.model_points(p_)[idx_k]
                r_data = (mp - tgt).ravel()
                r_reg = np.sqrt(self.reg) * p_[7:]   # E_reg: pull alpha towards 0
                return np.concatenate([r_data, r_reg])

            sol = least_squares(residual, p, method="trf", bounds=(lo, hi), max_nfev=200)
            p = sol.x

            rmse_mm = np.sqrt(np.mean(dist[keep] ** 2))   # mm, on kept points
            ang = np.degrees(np.linalg.norm(p[:3]))
            print(f"  iter {it:2d} | RMSE {rmse_mm:5.1f} mm | "
                  f"scale {np.exp(p[6]):.3f} | rot {ang:5.1f} deg | "
                  f"|alpha| {np.linalg.norm(p[7:]):5.2f}")
        return p


def _extent(points):
    return float(np.linalg.norm(points.max(0) - points.min(0)))
