# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-06-12.
# Analysis-by-synthesis fit (Python proof-of-concept). Mirrors C++ Optimizer.
#
# PROOF OF CONCEPT, not the final method. It fits the BFM to the DEPTH point
# cloud (the RGB-D modality) with iterative-closest-point + Levenberg-Marquardt:
#
#   parameters p = [ rotation(3, axis-angle), translation(3),
#                    log-scale(1), shape coeffs alpha(K) ]
#
# Each outer iteration:
#   1. transform the model with the current p
#   2. find, for every target point, the nearest model vertex   (ICP correspondences)
#   3. run Levenberg-Marquardt to reduce  ||model - target||^2 + reg*||alpha||^2
#
# The dense PHOTOMETRIC term, the SPARSE landmark term and EXPRESSION are left
# out on purpose -- those are the later milestones. This already demonstrates the
# loop: "predict the face parameters in N iterations".
# =============================================================================
import numpy as np
from scipy.optimize import least_squares
from scipy.spatial import cKDTree


def axis_angle_to_R(r):
    """Rodrigues' formula: axis-angle vector (3,) -> rotation matrix (3, 3)."""
    theta = np.linalg.norm(r)
    if theta < 1e-12:
        return np.eye(3)
    k = r / theta
    K = np.array([[0, -k[2], k[1]],
                  [k[2], 0, -k[0]],
                  [-k[1], k[0], 0]])
    return np.eye(3) + np.sin(theta) * K + (1 - np.cos(theta)) * (K @ K)


class Fitter:
    def __init__(self, bfm, n_shape=30, reg=2.0, n_model_pts=6000,
                 sparse_landmark_weight=1.8):
        self.n_shape = n_shape
        self.reg = reg
        self.sparse_landmark_weight = sparse_landmark_weight
        self.bfm = bfm

        # Subsample the model vertices for speed (full mesh = 53k vertices).
        stride = max(1, bfm.n_vertices // n_model_pts)
        sub = np.arange(0, bfm.n_vertices, stride)
        rows = (3 * sub[:, None] + np.array([0, 1, 2])).reshape(-1)  # (3S,)

        # Everything in MILLIMETRES (the BFM's native unit), centred on the
        # mean-face centroid. Working in mm keeps the regulariser physically
        # meaningful: reg ~ (depth noise in mm)^2.
        self.mean_sub = bfm.shape_mean[rows].reshape(-1, 3)                 # (S, 3) mm
        self.basis_sub = bfm.shape_basis[rows][:, :n_shape].reshape(-1, 3, n_shape)  # mm
        self.std = bfm.shape_std[:n_shape]
        self.c0 = self.mean_sub.mean(axis=0)

        # 180 deg about Y: BFM looks +z, we want the face looking at the camera (-z).
        self.R_init = np.diag([-1.0, 1.0, -1.0])

    # ---- the parametric model: p -> world-space vertices ---------------------
    def model_points(self, p):
        alpha = p[7:]
        V = self.mean_sub + (self.basis_sub * (alpha * self.std)).sum(axis=2)  # (S, 3)
        V = V - self.c0
        R = axis_angle_to_R(p[:3])
        s = np.exp(p[6])
        return (s * (R @ (self.R_init @ V.T))).T + p[3:6]

    # ---- apply the current pose transform to a set of 3D points ----------
    def transform_points(self, pts, p):
        R = axis_angle_to_R(p[:3])
        s = np.exp(p[6])
        return (s * (R @ (self.R_init @ (pts - self.c0).T))).T + p[3:6]

    # ---- project camera-frame points into pixels ---------------------------
    @staticmethod
    def project(points, K):
        X, Y, Z = points[:, 0], points[:, 1], points[:, 2]
        Z_safe = np.maximum(Z, 1e-6)
        u = K["fx"] * X / Z_safe + K["cx"]
        v = -K["fy"] * Y / Z_safe + K["cy"]
        return np.stack([u, v], axis=1)

    # ---- run the fit ---------------------------------------------------------
    def fit(self, target, K, landmark_2d=None, landmark_vertex_indices=None,
            n_iters=12, trim_percentile=80, use_dense=True):
        target = np.asarray(target)
        K = {k: float(v) for k, v in dict(K).items()}
        required = ("fx", "fy", "cx", "cy")
        if not all(name in K for name in required):
            raise ValueError("Intrinsics K must contain fx, fy, cx, cy")

        if landmark_2d is not None and landmark_vertex_indices is not None:
            landmark_2d = np.asarray(landmark_2d, dtype=np.float64).reshape(-1, 2)
            landmark_vertex_indices = np.asarray(landmark_vertex_indices, dtype=np.int32)
            if landmark_2d.shape[0] != landmark_vertex_indices.shape[0]:
                raise ValueError("landmark_2d and landmark_vertex_indices must have same length")
        else:
            landmark_2d = None
            landmark_vertex_indices = None

        Kshape = self.n_shape
        p = np.r_[0.0, 0.0, 0.0, target.mean(axis=0), 0.0, np.zeros(Kshape)]

        lo = np.r_[[-np.pi] * 3, [-np.inf] * 3, np.log(0.8), [-3.0] * Kshape]
        hi = np.r_[[np.pi] * 3, [np.inf] * 3, np.log(1.3), [3.0] * Kshape]

        def compute_landmark_rmse(p_):
            if landmark_2d is None:
                return None
            lm3d = self.bfm.shape(p_[7:])[landmark_vertex_indices]
            lm3d = self.transform_points(lm3d, p_)
            uv = self.project(lm3d, K)
            return float(np.sqrt(np.mean(np.sum((uv - landmark_2d) ** 2, axis=1))))

        initial_lm_rmse = compute_landmark_rmse(p)
        if initial_lm_rmse is not None:
            print(f"[fit] landmark RMSE before optimization: {initial_lm_rmse:.2f} px")

        print(f"[fit] target points: {len(target)},  params: {len(p)}")
        for it in range(n_iters):
            dist, idx = cKDTree(self.model_points(p)).query(target)
            thresh = np.percentile(dist, trim_percentile)
            keep = dist <= thresh
            tgt, idx_k = target[keep], idx[keep]

            def r_data(p_):
                model_pts = self.model_points(p_)
                return (model_pts[idx_k] - tgt).ravel()

            def r_lm(p_):
                lm3d = self.bfm.shape(p_[7:])[landmark_vertex_indices]
                lm3d = self.transform_points(lm3d, p_)
                uv = self.project(lm3d, K)
                return np.sqrt(self.sparse_landmark_weight) * (uv - landmark_2d).ravel()

            def r_reg(p_):
                return np.sqrt(self.reg) * p_[7:]

            def residual(p_):
                residual_blocks = []
                if use_dense:
                    residual_blocks.append(r_data(p_))
                if landmark_2d is not None:
                    residual_blocks.append(r_lm(p_))
                residual_blocks.append(r_reg(p_))
                return np.concatenate(residual_blocks)

            sol = least_squares(residual, p, method="trf", bounds=(lo, hi),
                                loss="soft_l1", f_scale=10.0, max_nfev=300)
            if not sol.success:
                print(f"[fit] optimizer warning: {sol.message}")
                print(f"cost: {sol.cost:.4f}, "
                      f"evaluations: {sol.nfev}, "
                      f"optimality: {sol.optimality:.4e}")
            p = sol.x

            if use_dense:
                dist_after, _ = cKDTree(self.model_points(p)).query(target)
                threshold_after = np.percentile(dist_after, trim_percentile)
                keep_after = dist_after <= threshold_after
                rmse_mm = np.sqrt(np.mean(dist_after[keep_after] ** 2))
                rmse_mm_str = f"{rmse_mm:5.1f} mm"
            else:
                rmse_mm_str = "n/a"

            lm_rmse = compute_landmark_rmse(p)
            lm_str = f" | lm {lm_rmse:5.2f} px" if lm_rmse is not None else ""
            ang = np.degrees(np.linalg.norm(p[:3]))
            print(f"  iter {it:2d} | RMSE {rmse_mm_str} | "
                  f"scale {np.exp(p[6]):.3f} | rot {ang:5.1f} deg | "
                  f"|alpha| {np.linalg.norm(p[7:]):5.2f}{lm_str}")

        if lm_rmse is not None:
            print(f"[fit] final landmark RMSE: {lm_rmse:.2f} px")
        return p

def _extent(points):
    return float(np.linalg.norm(points.max(0) - points.min(0)))
