# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-07-02.
# Downloader for the Biwi Kinect Head Pose Database (24 sequences, 20 people).
#
#   python3 python/get_biwi.py 02 05        # fetch sequences 02 and 05
#   python3 python/get_biwi.py --list       # show what is available / present
#
# The official ETH download (data.vision.ee.ethz.ch) is dead (403), so this
# pulls from a Hugging Face mirror that hosts the original archive split into
# two zips (BK-1.zip: seqs 01-10, BK-2.zip: seqs 11-24, ~6 GB together).
# Instead of downloading a whole zip, we read the zip's central directory via
# HTTP range requests (remotezip), then fetch ONLY the contiguous byte range
# of the requested sequence (~200-450 MB) and inflate it locally, CRC-checked.
# Partial downloads land in data/biwi/.parts/ and resume on re-run.
#
# License note: Biwi is research/education-only (like the BFM). data/ is
# gitignored — keep it that way.
# =============================================================================
import argparse
import binascii
import os
import struct
import sys
import zlib

import requests
from remotezip import RemoteZip

BASE = "https://huggingface.co/datasets/ZihanWang1029/BIWI/resolve/main/BIWI"
SEQ_TO_ZIP = {f"{i:02d}": "BK-1.zip" for i in range(1, 11)}
SEQ_TO_ZIP.update({f"{i:02d}": "BK-2.zip" for i in range(11, 25)})
ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "data", "biwi")


def central_directory(zip_name: str):
    """Fetch the remote zip's member list once (a few small range requests)."""
    with RemoteZip(f"{BASE}/{zip_name}") as z:
        return z.infolist(), z.start_dir


def sequence_span(infos, central_dir_start: int, seq: str):
    """Byte range [start, end) of one sequence inside the zip, plus the
    central-directory records needed to extract its members."""
    members = [i for i in infos if i.filename.startswith(seq + "/")]
    if not members:
        raise SystemExit(f"sequence {seq} not found in the archive")
    start = min(i.header_offset for i in members)
    last = max(i.header_offset for i in members)
    after = [i.header_offset for i in infos if i.header_offset > last]
    end = min(after) if after else central_dir_start
    return start, end, members


def download_range(zip_name: str, start: int, end: int, part_path: str) -> None:
    """Fetch bytes [start, end) into part_path, resuming a shorter file."""
    expected = end - start
    have = os.path.getsize(part_path) if os.path.exists(part_path) else 0
    if have > expected:                      # stale range definition -> redo
        os.remove(part_path)
        have = 0
    if have == expected:
        print(f"  part already complete ({expected / 1e6:.0f} MB)")
        return
    headers = {"Range": f"bytes={start + have}-{end - 1}"}
    print(f"  downloading {(expected - have) / 1e6:.0f} MB "
          f"({'resume' if have else 'fresh'}) ...")
    with requests.get(f"{BASE}/{zip_name}", headers=headers,
                      stream=True, timeout=60) as r:
        r.raise_for_status()
        with open(part_path, "ab") as f:
            for chunk in r.iter_content(1 << 20):
                f.write(chunk)
    if os.path.getsize(part_path) != expected:
        raise SystemExit("download incomplete — re-run to resume")


def extract(part_path: str, base_offset: int, members, out_root: str) -> int:
    """Inflate members out of the partial zip; every file is CRC-verified."""
    n = 0
    with open(part_path, "rb") as part:
        for info in members:
            if info.is_dir():
                continue
            part.seek(info.header_offset - base_offset)
            header = part.read(30)
            assert header[:4] == b"PK\x03\x04", info.filename
            name_len, extra_len = struct.unpack("<HH", header[26:30])
            part.seek(info.header_offset - base_offset + 30 + name_len + extra_len)
            blob = part.read(info.compress_size)
            if info.compress_type == 0:
                data = blob
            elif info.compress_type == 8:
                data = zlib.decompressobj(-15).decompress(blob)
            else:
                raise SystemExit(f"unsupported compression in {info.filename}")
            if binascii.crc32(data) & 0xFFFFFFFF != info.CRC:
                raise SystemExit(f"CRC mismatch: {info.filename} — delete "
                                 f"{part_path} and re-run")
            dest = os.path.join(out_root, info.filename)
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "wb") as f:
                f.write(data)
            n += 1
    return n


def fetch_sequence(seq: str, infos, central_dir_start: int) -> None:
    zip_name = SEQ_TO_ZIP[seq]
    print(f"sequence {seq}  (from {zip_name})")
    start, end, members = sequence_span(infos, central_dir_start, seq)
    parts_dir = os.path.join(ROOT, ".parts")
    os.makedirs(parts_dir, exist_ok=True)
    part_path = os.path.join(parts_dir, f"{zip_name}_{seq}.part")
    download_range(zip_name, start, end, part_path)
    n = extract(part_path, start, members, ROOT)
    os.remove(part_path)
    print(f"  extracted {n} files -> {os.path.join(ROOT, seq)}/")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sequences", nargs="*",
                        help="sequence numbers 01..24 (e.g. 02 05 11)")
    parser.add_argument("--all", action="store_true",
                        help="fetch every sequence that is not present yet (~7.5 GB total)")
    parser.add_argument("--list", action="store_true",
                        help="show available and already-downloaded sequences")
    args = parser.parse_args()

    if args.list or not (args.sequences or args.all):
        for seq in sorted(SEQ_TO_ZIP):
            here = os.path.isdir(os.path.join(ROOT, seq))
            print(f"  {seq}  {SEQ_TO_ZIP[seq]}  {'[downloaded]' if here else ''}")
        if not (args.sequences or args.all):
            sys.exit(0)

    wanted = sorted(SEQ_TO_ZIP) if args.all else [f"{int(s):02d}" for s in args.sequences]
    for seq in wanted:
        if seq not in SEQ_TO_ZIP:
            raise SystemExit(f"unknown sequence {seq} (valid: 01..24)")
    todo = [s for s in wanted if not os.path.isdir(os.path.join(ROOT, s))]
    for seq in set(wanted) - set(todo):
        print(f"sequence {seq} already present — skipping")

    # one central-directory fetch per zip, shared by all its sequences
    for zip_name in sorted({SEQ_TO_ZIP[s] for s in todo}):
        infos, central_dir_start = central_directory(zip_name)
        for seq in [s for s in todo if SEQ_TO_ZIP[s] == zip_name]:
            fetch_sequence(seq, infos, central_dir_start)


if __name__ == "__main__":
    main()
