# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-06-12.
# Proof-of-concept pipeline:
#   load BFM  ->  load a Pandora frame  ->  fit the face parameters over N
#   iterations  ->  render the result  ->  save input-vs-reconstruction image.
#
# Run from the PROJECT ROOT:   python3 python/main.py
# Output:                      data/out/fit_result.png
# =============================================================================
import os

import matplotlib
matplotlib.use("Agg")              # no display needed (works in a container)
import matplotlib.pyplot as plt
import numpy as np
import yaml

from bfm import BFM
from dataset import PandoraFrame, backproject, crop_head, keep_front, head_center
from fit import Fitter
from render import render, colorize_depth

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load_config():
    with open(os.path.join(HERE, "config.yaml")) as f:
        return yaml.safe_load(f)


def main():
    cfg = load_config()
    K = cfg["dataset"]["intrinsics"]
    frame_idx = cfg["dataset"]["frame_index"]

    # 1. BFM (the generator)
    bfm = BFM(os.path.join(ROOT, cfg["bfm"]["model_path"]))

    # 2. one Pandora frame
    frame = PandoraFrame(os.path.join(ROOT, cfg["dataset"]["root"]), frame_idx)

    # 3. depth -> 3D point cloud -> crop the face. Backprojection is in metres;
    #    the fitter works in millimetres (BFM units), so convert.
    cloud = backproject(frame.depth_mm, K)
    center = head_center(frame)
    face = keep_front(crop_head(cloud, center, radius=0.13), slab=0.10)
    if len(face) > 2500:                       # subsample for a fast fit
        face = face[np.random.RandomState(0).choice(len(face), 2500, replace=False)]
    face_mm = face * 1000.0
    print(f"[data] face cloud: {len(face)} points around {np.round(center, 3)} m")

    # 4. fit the parameters (analysis-by-synthesis loop)
    fitter = Fitter(bfm,
                    n_shape=cfg["fit"]["n_shape_coeffs"],
                    reg=cfg["fit"]["regularization"])
    p = fitter.fit(face_mm, n_iters=cfg["fit"]["n_iters"])

    # 5. render the fitted FULL-resolution mesh with its albedo.
    #    Apply the same transform the fitter used, but to all 53k vertices (mm):
    from fit import axis_angle_to_R
    alpha = p[7:]
    V = bfm.shape(alpha) - fitter.c0
    Rm = axis_angle_to_R(p[:3])
    s = np.exp(p[6])
    world = (s * (Rm @ (fitter.R_init @ V.T))).T + p[3:6]
    H, W = frame.depth_mm.shape
    recon = render(world, bfm.albedo(), K, height=H, width=W)

    # zoom both depth and reconstruction to the fitted face's bounding box so the
    # input-vs-reconstruction comparison is actually legible.
    from render import project
    u, v, z = project(world, K)
    m = z > 1e-3
    pad = 30
    c0, c1 = max(0, int(u[m].min()) - pad), min(W, int(u[m].max()) + pad)
    r0, r1 = max(0, int(v[m].min()) - pad), min(H, int(v[m].max()) + pad)
    depth_vis = colorize_depth(frame.depth_mm)

    # 6. save: input depth (face) vs reconstruction (face) (+ RGB for context)
    #ist alles nur um Bilder darszustellen,
    out_dir = os.path.join(ROOT, cfg["output"]["dir"])
    os.makedirs(out_dir, exist_ok=True)
    fig, ax = plt.subplots(1, 3, figsize=(15, 5))
    ax[0].imshow(frame.rgb)
    ax[0].set_title("RGB (context)")
    ax[1].imshow(depth_vis[r0:r1, c0:c1])
    ax[1].set_title("Input depth (face)")
    ax[2].imshow(recon[r0:r1, c0:c1])
    ax[2].set_title("Reconstructed BFM fit")
    for a in ax:
        a.axis("off")
    out_path = os.path.join(out_dir, "fit_result.png")
    fig.tight_layout(); fig.savefig(out_path, dpi=120)
    print(f"\n[done] wrote {out_path}")


if __name__ == "__main__":
    main()
