# =============================================================================
# Generated by Claude (Anthropic Claude Code) on 2026-06-12.
# Minimal renderer (Python proof-of-concept). Mirrors the future C++ Renderer.
#
# This is a simple z-buffered point splat -- NOT the differentiable triangle
# rasteriser the paper describes. It is just enough to SEE the fitted face.
# =============================================================================
import cv2
import numpy as np


def project(points, K):
    """3D camera-frame points (metres) -> pixel coords. Returns (u, v, z)."""
    X, Y, Z = points[:, 0], points[:, 1], points[:, 2]
    u = K["fx"] * X / Z + K["cx"]
    v = -K["fy"] * Y / Z + K["cy"]
    return u, v, Z


def render(points, colors, K, height, width):
    """Render coloured 3D points into an (H, W, 3) image with a z-buffer.

    Nearest point per pixel wins; a small dilation fills the gaps between splats.
    `colors` are RGB in [0, 1].
    """
    u, v, z = project(points, K)
    ui = np.round(u).astype(int)
    vi = np.round(v).astype(int)

    inside = (ui >= 0) & (ui < width) & (vi >= 0) & (vi < height) & (z > 1e-3)
    ui, vi, z = ui[inside], vi[inside], z[inside]
    col = (colors[inside] * 255).astype(np.uint8)

    img = np.zeros((height, width, 3), dtype=np.uint8)
    zbuf = np.full((height, width), np.inf)

    order = np.argsort(-z)                 # far -> near, so near overwrites
    img[vi[order], ui[order]] = col[order]
    zbuf[vi[order], ui[order]] = z[order]

    # Fill the small holes between projected points.
    mask = (zbuf == np.inf).astype(np.uint8)
    img = cv2.morphologyEx(img, cv2.MORPH_CLOSE, np.ones((3, 3), np.uint8))
    return img


def colorize_depth(depth_mm):
    """Turn the (almost-black) 16-bit depth into a viewable colour image,
    normalised over its VALID range -- this is how you 'see' the depth."""
    valid = depth_mm > 0
    out = np.zeros_like(depth_mm, dtype=np.uint8)
    if valid.any():
        lo, hi = depth_mm[valid].min(), depth_mm[valid].max()
        norm = np.zeros_like(depth_mm, dtype=np.float32)
        norm[valid] = (depth_mm[valid] - lo) / max(hi - lo, 1)
        out = (norm * 255).astype(np.uint8)
    return cv2.applyColorMap(out, cv2.COLORMAP_TURBO)[:, :, ::-1]  # BGR->RGB
